-- =====================================================================
-- MotoIntel schema (PostgreSQL 16). Snake_case names; Postgres types only.
-- Two domains: Catalog (Domain 1) and Market (Domain 2), plus jobs.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Catalog (Domain 1)
-- ---------------------------------------------------------------------
CREATE TABLE manufacturers (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text        NOT NULL,
    normalized_name text        NOT NULL UNIQUE,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE motorcycle_models (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_id       bigint NOT NULL REFERENCES manufacturers (id),
    name                  text   NOT NULL,
    normalized_name       text   NOT NULL,
    production_start_year int,
    production_end_year   int,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_model_manuf_normname UNIQUE (manufacturer_id, normalized_name)
);
CREATE INDEX idx_models_manufacturer ON motorcycle_models (manufacturer_id);
CREATE INDEX idx_models_normname ON motorcycle_models (normalized_name);

CREATE TABLE motorcycle_variants (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id  bigint NOT NULL REFERENCES motorcycle_models (id),
    name      text   NOT NULL,
    year_from int,
    year_to   int
);
CREATE INDEX idx_variants_model ON motorcycle_variants (model_id);

CREATE TABLE motorcycle_specs (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id           bigint NOT NULL REFERENCES motorcycle_models (id),
    variant_id         bigint REFERENCES motorcycle_variants (id),
    engine_capacity_cc numeric,
    power_kw           numeric,
    torque_nm          numeric,
    dry_weight_kg      numeric,
    wet_weight_kg      numeric,
    seat_height_mm     numeric,
    fuel_capacity_l    numeric,
    top_speed_kmh      numeric,
    cooling            text,
    transmission       text,
    final_drive        text,
    abs                boolean,
    is_electric        boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_specs_model ON motorcycle_specs (model_id);

CREATE TABLE motorcycle_images (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id   bigint NOT NULL REFERENCES motorcycle_models (id),
    storage_ref text  NOT NULL,
    source_url text,
    width      int,
    height     int
);
CREATE INDEX idx_images_model ON motorcycle_images (model_id);

CREATE TABLE model_aliases (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id         bigint NOT NULL REFERENCES motorcycle_models (id),
    alias            text   NOT NULL,
    normalized_alias text   NOT NULL
);
CREATE INDEX idx_aliases_normalized ON model_aliases (normalized_alias);
CREATE INDEX idx_aliases_model ON model_aliases (model_id);

CREATE TABLE catalog_sources (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text NOT NULL,
    source_type       text,
    access_method     text,
    base_url          text,
    enabled           boolean NOT NULL DEFAULT false,
    compliance_status text,
    schedule_cron     text,
    last_run_at       timestamptz,
    next_run_at       timestamptz
);

CREATE TABLE catalog_source_pages (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     bigint NOT NULL REFERENCES catalog_sources (id),
    url           text NOT NULL UNIQUE,
    page_type     text,
    discovered_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE catalog_source_snapshots (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id      bigint NOT NULL REFERENCES catalog_source_pages (id),
    storage_ref  text,
    fetched_at   timestamptz NOT NULL DEFAULT now(),
    http_status  int,
    content_hash text
);

CREATE TABLE spec_evidence (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_id     bigint NOT NULL REFERENCES motorcycle_specs (id),
    snapshot_id bigint REFERENCES catalog_source_snapshots (id),
    field_name  text,
    raw_value   text
);

-- ---------------------------------------------------------------------
-- Sources / Jobs
-- ---------------------------------------------------------------------
CREATE TABLE ingestion_jobs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          text NOT NULL,
    source_id     bigint,
    status        text NOT NULL,
    started_at    timestamptz,
    finished_at   timestamptz,
    discovered    int NOT NULL DEFAULT 0,
    fetched       int NOT NULL DEFAULT 0,
    parsed        int NOT NULL DEFAULT 0,
    inserted      int NOT NULL DEFAULT 0,
    updated       int NOT NULL DEFAULT 0,
    failed        int NOT NULL DEFAULT 0,
    error_summary text
);
CREATE INDEX idx_jobs_status ON ingestion_jobs (status);
CREATE INDEX idx_jobs_type ON ingestion_jobs (type);
CREATE INDEX idx_jobs_started ON ingestion_jobs (started_at);

CREATE TABLE ingestion_job_errors (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     bigint NOT NULL REFERENCES ingestion_jobs (id),
    url        text,
    stage      text,
    message    text,
    detail     text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_job_errors_job ON ingestion_job_errors (job_id);

-- ---------------------------------------------------------------------
-- Market (Domain 2)
-- ---------------------------------------------------------------------
CREATE TABLE market_sources (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text NOT NULL,
    source_type       text,
    access_method     text,
    base_url          text,
    enabled           boolean NOT NULL DEFAULT false,
    compliance_status text,
    schedule_cron     text,
    last_run_at       timestamptz,
    next_run_at       timestamptz
);

CREATE TABLE market_search_queries (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_source_id bigint NOT NULL REFERENCES market_sources (id),
    query            text NOT NULL,
    enabled          boolean NOT NULL DEFAULT true
);

CREATE TABLE market_listings (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_source_id          bigint REFERENCES market_sources (id),
    source                    text NOT NULL,
    external_id               text,
    url                       text NOT NULL,
    normalized_url            text NOT NULL,
    title                     text NOT NULL,
    description               text,
    price                     numeric,
    currency                  text,
    location                  text,
    seller_type               text,
    posted_date               date,
    first_observed_at         timestamptz NOT NULL DEFAULT now(),
    last_observed_at          timestamptz NOT NULL DEFAULT now(),
    status                    text NOT NULL DEFAULT 'active',
    extracted_year            int,
    extracted_manufacturer    text,
    extracted_model_text      text,
    extracted_capacity_cc     numeric,
    extracted_mileage_km      int,
    consecutive_missing_count int NOT NULL DEFAULT 0,
    latest_snapshot_id        bigint   -- circular ref to market_listing_snapshots; intentionally NOT an inline FK
);
-- Dedupe keys (§3): (source, external_id) when present, else (source, normalized_url)
CREATE UNIQUE INDEX uq_listing_source_extid ON market_listings (source, external_id) WHERE external_id IS NOT NULL;
CREATE UNIQUE INDEX uq_listing_source_url   ON market_listings (source, normalized_url) WHERE external_id IS NULL;
CREATE INDEX idx_listings_status ON market_listings (status);
CREATE INDEX idx_listings_price ON market_listings (price);
CREATE INDEX idx_listings_source ON market_listings (source);

CREATE TABLE market_listing_snapshots (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id   bigint NOT NULL REFERENCES market_listings (id),
    storage_ref  text,
    captured_at  timestamptz NOT NULL DEFAULT now(),
    content_hash text
);
CREATE INDEX idx_listing_snapshots_listing ON market_listing_snapshots (listing_id);

CREATE TABLE market_listing_images (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  bigint NOT NULL REFERENCES market_listings (id),
    storage_ref text NOT NULL,
    source_url  text
);
CREATE INDEX idx_listing_images_listing ON market_listing_images (listing_id);

CREATE TABLE listing_price_history (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  bigint NOT NULL REFERENCES market_listings (id),
    price       numeric NOT NULL,
    currency    text,
    observed_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_price_history_listing_obs ON listing_price_history (listing_id, observed_at);

CREATE TABLE listing_status_history (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint NOT NULL REFERENCES market_listings (id),
    status     text NOT NULL,
    at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_status_history_listing ON listing_status_history (listing_id);

CREATE TABLE listing_model_matches (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  bigint NOT NULL UNIQUE REFERENCES market_listings (id),
    model_id    bigint REFERENCES motorcycle_models (id),
    variant_id  bigint REFERENCES motorcycle_variants (id),
    status      text NOT NULL,
    confidence  numeric,
    explanation text,
    is_manual   boolean NOT NULL DEFAULT false,
    decided_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_matches_status ON listing_model_matches (status);
CREATE INDEX idx_matches_model ON listing_model_matches (model_id);

CREATE TABLE match_candidates (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  bigint NOT NULL REFERENCES market_listings (id),
    model_id    bigint NOT NULL REFERENCES motorcycle_models (id),
    variant_id  bigint REFERENCES motorcycle_variants (id),
    confidence  numeric,
    explanation text,
    rank        int
);
CREATE INDEX idx_candidates_listing ON match_candidates (listing_id);
